version: '3.9'
services:
  wordpress:
    # default port 9000 (FastCGI)
    container_name: wp-wordpress
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - wordpress
    volumes:
      # - ./wp-config.php:/var/www/html/wp-config.php
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./sites/:/var/www/html
    # environment:
    #   - WORDPRESS_DB_HOST="host.docker.internal"
    #   - WORDPRESS_DB_NAME="k7p1k4e2_LAl"
    #   - WORDPRESS_DB_USER="root"
    #   - WORDPRESS_DB_PASSWORD="12345"
    #   - WORDPRESS_DEBUG="true"
    environment:
      WORDPRESS_DB_HOST: "host.docker.internal"
      WORDPRESS_DB_NAME: "k7p1k4e2_LAl"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DEBUG: "true"

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8087:80" # http
      - "8447:443" # https
    volumes:
      - ./sites/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/ssl:ro
      # - ${NGINX_LOGS}:/var/log/nginx
    environment:
      WORDPRESS_DB_HOST: "host.docker.internal"
      WORDPRESS_DB_NAME: "k7p1k4e2_LAl"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DEBUG: "true"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
